apiVersion: v1
kind: Secret
metadata:
  name: {{ include "middlewareapp.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "middlewareapp.labels" . | nindent 4 }}
type: Opaque
data:
  LLM_API_KEY: {{ .Values.secrets.LLM_API_KEY | b64enc | quote }}
